### ISSUE TITLE
ImportError: DLL load failed while importing _core: The specified module could not be found.

### ISSUE THREAD

**Issue by Grey-Lancaster** [ppamment/wledcast#1]
Error when starting

````
Microsoft Windows [Version 10.0.19045.3693]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Grey>wledcast
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Grey\AppData\Local\Programs\Python\Python312\Scripts\wledcast.exe\__main__.py", line 4, in <module>
  File "C:\Users\Grey\AppData\Local\Programs\Python\Python312\Lib\site-packages\wledcast\main.py", line 7, in <module>
    from . import image_processor
  File "C:\Users\Grey\AppData\Local\Programs\Python\Python312\Lib\site-packages\wledcast\image_processor.py", line 5, in <module>
    import wx
  File "C:\Users\Grey\AppData\Local\Programs\Python\Python312\Lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Users\Grey\AppData\Local\Programs\Python\Python312\Lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ImportError: DLL load failed while importing _core: The specified module could not be found.

C:\Users\Grey>
````

**Comment by ppamment** [comment]
Not 100% certain, but I think you need to install Visual C++ runtime 2015 available here:
https://www.microsoft.com/en-us/download/details.aspx?id=53840

There are some issues raised on wxPython about this and they seem to have had some versions of the package released without some required dlls, so if that doesn't fix it, can you run pip list and let me know which versions of wxPython and wxWidgets you have installed. I also didn't try this with python 3.12 yet.

**Comment by Grey-Lancaster** [comment]
That must have been it.  Since then I installed Visual code and platformio and now it works.
Now to figure out what it does :-)

**Comment by Grey-Lancaster** [comment]
thanks
